# Generated by Django 4.2.5 on 2023-09-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                (
                    'frequency',
                    models.CharField(
                        choices=[
                            ('Thirty Minutes', 'Thirty Mins'),
                            ('Hourly', 'Hourly'),
                            ('Weekly', 'Weekly'),
                            ('Biweekly', 'Biweekly'),
                            ('Monthly', 'Monthly'),
                        ],
                        default='Thirty Minutes',
                        max_length=15,
                    ),
                ),
                (
                    'beneficiary',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='disbursements',
                        to='beneficiaries.beneficiary',
                    ),
                ),
            ],
        ),
    ]
