# Generated by Django 4.2.5 on 2023-09-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('beneficiaries', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                (
                    'frequency',
                    models.CharField(
                        choices=[
                            ('Thirty Minutes', 'Thirty Mins'),
                            ('Hourly', 'Hourly'),
                            ('Weekly', 'Weekly'),
                            ('Biweekly', 'Biweekly'),
                            ('Monthly', 'Monthly'),
                        ],
                        default='Thirty Minutes',
                        max_length=15,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        default='active',
                        verbose_name='status',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('next_run_timestamp', models.DateTimeField(blank=True, null=True)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='disbursements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'beneficiary',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='disbursements',
                        to='beneficiaries.beneficiary',
                    ),
                ),
            ],
        ),
    ]
