# Generated by Django 4.2.5 on 2023-09-09 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('disbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(2023, 9, 9, 10, 47, 45, 366537, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
