# Generated by Django 4.2.5 on 2023-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('disbursements', '0002_alter_disbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive')],
                default='active',
                max_length=20,
                verbose_name='status',
            ),
        ),
    ]
