# Generated by Django 4.2.5 on 2023-09-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit_account_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit_account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit_bank_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
        migrations.AddField(
            model_name='account',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.IntegerField(verbose_name='postal code')),
                (
                    'gender',
                    models.CharField(
                        choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')],
                        max_length=20,
                        verbose_name='gender',
                    ),
                ),
                (
                    'country',
                    models.CharField(choices=[('NG', 'Nigeria')], default='NG', max_length=10, verbose_name='country'),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('FCT', 'Fct'),
                            ('OYO', 'Oyo'),
                            ('IMO', 'Imo'),
                            ('EDO', 'Edo'),
                            ('KANO', 'Kano'),
                            ('ONDO', 'Ondo'),
                            ('OSUN', 'Osun'),
                            ('OGUN', 'Ogun'),
                            ('KOGI', 'Kogi'),
                            ('YOBE', 'Yobe'),
                            ('ABIA', 'Abia'),
                            ('ENUGU', 'Enugu'),
                            ('LAGOS', 'Lagos'),
                            ('NIGER', 'Niger'),
                            ('BENUE', 'Benue'),
                            ('GOMBE', 'Gombe'),
                            ('KWARA', 'Kwara'),
                            ('EKITI', 'Ekiti'),
                            ('DELTA', 'Delta'),
                            ('BORNO', 'Borno'),
                            ('KEBBI', 'Kebbi'),
                            ('KADUNA', 'Kaduna'),
                            ('BAUCHI', 'Bauchi'),
                            ('EBONYI', 'Ebonyi'),
                            ('JIGAWA', 'Jigawa'),
                            ('SOKOTO', 'Sokoto'),
                            ('RIVERS', 'Rivers'),
                            ('TARABA', 'Taraba'),
                            ('ZAMFARA', 'Zamfara'),
                            ('PLATEAU', 'Plateau'),
                            ('ADAMAWA', 'Adamawa'),
                            ('ANAMBRA', 'Anambra'),
                            ('KATSINA', 'Katsina'),
                            ('BAYELSA', 'Bayelsa'),
                            ('NASARAWA', 'Nasarawa'),
                            ('AKWA_IBOM', 'Akwa Ibom'),
                            ('CROSS_RIVER', 'Cross River'),
                        ],
                        max_length=20,
                        verbose_name='state',
                    ),
                ),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                (
                    'bvn',
                    models.CharField(
                        blank=True, editable=False, max_length=128, null=True, verbose_name='Bank Verification Number'
                    ),
                ),
                ('customer_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='customer id')),
                (
                    'account',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                (
                    'currency',
                    models.CharField(
                        choices=[('NGN', 'Naira'), ('USD', 'Dollar')],
                        default='NGN',
                        max_length=10,
                        verbose_name='currency',
                    ),
                ),
                ('provider_account_id', models.CharField(max_length=150, verbose_name='provider account id')),
                ('account_number', models.CharField(max_length=11, verbose_name='deposit account number')),
                ('account_name', models.CharField(max_length=150, verbose_name='deposit account name')),
                ('bank_name', models.CharField(max_length=150, verbose_name='deposit bank name')),
                ('bank_code', models.CharField(max_length=150, verbose_name='deposit bank code')),
                (
                    '_balance',
                    models.DecimalField(
                        db_column='balance', decimal_places=6, default=0.0, editable=False, max_digits=15
                    ),
                ),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_reason', models.CharField(blank=True, default='', max_length=1024)),
                (
                    'account',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='wallet',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'profile',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='wallet',
                        to='accounts.profile',
                    ),
                ),
            ],
            options={
                'unique_together': {('account', 'profile', 'currency')},
            },
        ),
    ]
