# Generated by Django 4.2.5 on 2023-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_account_balance_account_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit_account_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='deposit account number'),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit_bank_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='deposit bank name'),
        ),
    ]
