# Generated by Django 4.2.5 on 2023-09-13 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disbursements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                (
                    'tx_type',
                    models.CharField(
                        choices=[
                            ('funding', 'Funding'),
                            ('bill payment', 'Bill Payment'),
                            ('disbursement', 'Disbursement'),
                        ],
                        max_length=100,
                        verbose_name='transaction type',
                    ),
                ),
                ('metadata', models.JSONField(default=dict, verbose_name='metadata')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                (
                    'currency',
                    models.CharField(
                        choices=[('NGN', 'Naira'), ('USD', 'Dollar')], max_length=3, verbose_name='currency'
                    ),
                ),
                ('anchor_ref', models.CharField(max_length=250, unique=True, verbose_name='anchor reference')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('failed', 'Failed'),
                            ('pending', 'Pending'),
                            ('reversed', 'Reversed'),
                            ('successful', 'Successful'),
                        ],
                        max_length=50,
                        verbose_name='status',
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'disbursement_event',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='disbursement_event_transactions',
                        to='disbursements.disbursementevent',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
