# Generated by Django 4.2.5 on 2023-09-09 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_tx_id', models.CharField(max_length=250, unique=True, verbose_name='anchor transaction id')),
                (
                    'tx_type',
                    models.CharField(
                        choices=[('funding', 'Funding'), ('disbursement', 'Disbursement')],
                        max_length=100,
                        verbose_name='transaction type',
                    ),
                ),
                ('destination', models.CharField(max_length=200, verbose_name='destination')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('failed', 'Failed'),
                            ('pending', 'Pending'),
                            ('reversed', 'Reversed'),
                            ('successful', 'Successful'),
                        ],
                        max_length=50,
                        verbose_name='status',
                    ),
                ),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('metadata', models.JSONField(default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
