# Generated by Django 4.2.5 on 2023-09-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('account_number', models.CharField(max_length=11, unique=True)),
                ('account_name', models.CharField(max_length=150, null=True)),
                ('bank_code', models.CharField(max_length=150, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=150, null=True)),
                ('counterparty_id', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='beneficiaries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
